// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVxxAbxJtOcospN9bKdxu4h2M3edToaDM',
    appId: '1:989948659929:web:7191fbd614a8125bad16c8',
    messagingSenderId: '989948659929',
    projectId: 'learnflow-ed84e',
    authDomain: 'learnflow-ed84e.firebaseapp.com',
    storageBucket: 'learnflow-ed84e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZNRrIPzdK1Bo_ECeVc1ODjUMk5hcx8RU',
    appId: '1:989948659929:android:fcc2df0c88ec89d3ad16c8',
    messagingSenderId: '989948659929',
    projectId: 'learnflow-ed84e',
    storageBucket: 'learnflow-ed84e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Nc4ImbwKPz0xKP9I11fCnnhjwitvSvE',
    appId: '1:989948659929:ios:390400cf0d3b233fad16c8',
    messagingSenderId: '989948659929',
    projectId: 'learnflow-ed84e',
    storageBucket: 'learnflow-ed84e.firebasestorage.app',
    iosBundleId: 'com.learnflow.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Nc4ImbwKPz0xKP9I11fCnnhjwitvSvE',
    appId: '1:989948659929:ios:ea36d469b69dbc45ad16c8',
    messagingSenderId: '989948659929',
    projectId: 'learnflow-ed84e',
    storageBucket: 'learnflow-ed84e.firebasestorage.app',
    iosBundleId: 'com.example.nha269',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVxxAbxJtOcospN9bKdxu4h2M3edToaDM',
    appId: '1:989948659929:web:72553c0d31c94ef6ad16c8',
    messagingSenderId: '989948659929',
    projectId: 'learnflow-ed84e',
    authDomain: 'learnflow-ed84e.firebaseapp.com',
    storageBucket: 'learnflow-ed84e.firebasestorage.app',
  );
}
